version: "3"

tasks:
  paper-build:
    desc: Build JOSS paper locally
    cmds:
      - |
        docker run --rm \
          --volume $PWD/paper:/data \
          --user $(id -u):$(id -g) \
          --env JOURNAL=joss \
          openjournals/inara
      - echo "Paper built!"
      - echo "Watching for changes"

  paper-preview:
    watch: true
    sources:
      - "paper/paper.md"
      - "paper/paper.bib"
    cmds:
      - task: paper-build
      - echo "Watching for changes"

  paper-wordcount:
    cmds:
      - pandoc paper/paper.md -t plain | wc -w
