# Generated by cpp11: do not edit by hand

caugi_create_amat_from_csr <- function(row_ptr, col_ids, type_codes, type) {
  .Call(`_caugi_caugi_create_amat_from_csr`, row_ptr, col_ids, type_codes, type)
}

caugi_create_csr_from_csr <- function(from, to, types, n_nodes_) {
  .Call(`_caugi_caugi_create_csr_from_csr`, from, to, types, n_nodes_)
}

caugi_create_csr_from_amat <- function(mat_, type) {
  .Call(`_caugi_caugi_create_csr_from_amat`, mat_, type)
}

caugi_create_csr_from_dense <- function(mat_) {
  .Call(`_caugi_caugi_create_csr_from_dense`, mat_)
}

caugi_create_csr_from_sparse <- function(mat_, directed) {
  .Call(`_caugi_caugi_create_csr_from_sparse`, mat_, directed)
}
