# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_caugi_wrappers", use_symbols = TRUE, package_name = "caugi")

#' @usage NULL
#' @useDynLib caugi, .registration = TRUE
NULL

edge_registry_new <- function() .Call(wrap__edge_registry_new)

edge_registry_register_builtins <- function(reg) invisible(.Call(wrap__edge_registry_register_builtins, reg))

edge_registry_seal <- function(reg) invisible(.Call(wrap__edge_registry_seal, reg))

edge_registry_len <- function(reg) .Call(wrap__edge_registry_len, reg)

edge_registry_register <- function(reg, glyph, tail_mark, head_mark, class, symmetric) .Call(wrap__edge_registry_register, reg, glyph, tail_mark, head_mark, class, symmetric)

edge_registry_code_of <- function(reg, glyphs) .Call(wrap__edge_registry_code_of, reg, glyphs)

edge_registry_spec_of_code <- function(reg, code) .Call(wrap__edge_registry_spec_of_code, reg, code)

rs_new <- function(reg, n, simple, class) .Call(wrap__rs_new, reg, n, simple, class)

rs_clone <- function(session) .Call(wrap__rs_clone, session)

rs_set_edges <- function(session, from, to, etype) invisible(.Call(wrap__rs_set_edges, session, from, to, etype))

rs_set_n <- function(session, n) invisible(.Call(wrap__rs_set_n, session, n))

rs_set_simple <- function(session, simple) invisible(.Call(wrap__rs_set_simple, session, simple))

rs_set_class <- function(session, class) invisible(.Call(wrap__rs_set_class, session, class))

rs_resolve_class <- function(session, class) .Call(wrap__rs_resolve_class, session, class)

rs_set_names <- function(session, names) invisible(.Call(wrap__rs_set_names, session, names))

rs_compute_layout <- function(session, method, packing_ratio) .Call(wrap__rs_compute_layout, session, method, packing_ratio)

rs_compute_bipartite_layout <- function(session, partition, orientation) .Call(wrap__rs_compute_bipartite_layout, session, partition, orientation)

rs_n <- function(session) .Call(wrap__rs_n, session)

rs_is_simple <- function(session) .Call(wrap__rs_is_simple, session)

rs_simple <- function(session) .Call(wrap__rs_simple, session)

rs_class <- function(session) .Call(wrap__rs_class, session)

rs_graph_class <- function(session) .Call(wrap__rs_graph_class, session)

rs_names <- function(session) .Call(wrap__rs_names, session)

rs_index_of <- function(session, name) .Call(wrap__rs_index_of, session, name)

rs_indices_of <- function(session, names) .Call(wrap__rs_indices_of, session, names)

rs_edges_df <- function(session) .Call(wrap__rs_edges_df, session)

rs_is_valid <- function(session) .Call(wrap__rs_is_valid, session)

rs_build <- function(session) invisible(.Call(wrap__rs_build, session))

rs_topological_sort <- function(session) .Call(wrap__rs_topological_sort, session)

rs_parents_of <- function(session, idxs) .Call(wrap__rs_parents_of, session, idxs)

rs_children_of <- function(session, idxs) .Call(wrap__rs_children_of, session, idxs)

rs_undirected_of <- function(session, idxs) .Call(wrap__rs_undirected_of, session, idxs)

rs_neighbors_of <- function(session, idxs, mode) .Call(wrap__rs_neighbors_of, session, idxs, mode)

rs_ancestors_of <- function(session, node) .Call(wrap__rs_ancestors_of, session, node)

rs_descendants_of <- function(session, node) .Call(wrap__rs_descendants_of, session, node)

rs_anteriors_of <- function(session, node) .Call(wrap__rs_anteriors_of, session, node)

rs_markov_blanket_of <- function(session, node) .Call(wrap__rs_markov_blanket_of, session, node)

rs_spouses_of <- function(session, idxs) .Call(wrap__rs_spouses_of, session, idxs)

rs_exogenous_nodes <- function(session, undirected_as_parents) .Call(wrap__rs_exogenous_nodes, session, undirected_as_parents)

rs_districts <- function(session) .Call(wrap__rs_districts, session)

rs_district_of <- function(session, idx) .Call(wrap__rs_district_of, session, idx)

rs_is_acyclic <- function(session) .Call(wrap__rs_is_acyclic, session)

rs_is_dag_type <- function(session) .Call(wrap__rs_is_dag_type, session)

rs_is_pdag_type <- function(session) .Call(wrap__rs_is_pdag_type, session)

rs_is_ug_type <- function(session) .Call(wrap__rs_is_ug_type, session)

rs_is_admg_type <- function(session) .Call(wrap__rs_is_admg_type, session)

rs_is_ag_type <- function(session) .Call(wrap__rs_is_ag_type, session)

rs_is_mag <- function(session) .Call(wrap__rs_is_mag, session)

rs_is_cpdag <- function(session) .Call(wrap__rs_is_cpdag, session)

rs_to_cpdag <- function(session) .Call(wrap__rs_to_cpdag, session)

rs_skeleton <- function(session) .Call(wrap__rs_skeleton, session)

rs_moralize <- function(session) .Call(wrap__rs_moralize, session)

rs_latent_project <- function(session, latents) .Call(wrap__rs_latent_project, session, latents)

rs_induced_subgraph <- function(session, keep) .Call(wrap__rs_induced_subgraph, session, keep)

rs_d_separated <- function(session, xs, ys, z) .Call(wrap__rs_d_separated, session, xs, ys, z)

rs_minimal_d_separator <- function(session, xs, ys, include, restrict) .Call(wrap__rs_minimal_d_separator, session, xs, ys, include, restrict)

rs_m_separated <- function(session, xs, ys, z) .Call(wrap__rs_m_separated, session, xs, ys, z)

rs_adjustment_set_parents <- function(session, xs, ys) .Call(wrap__rs_adjustment_set_parents, session, xs, ys)

rs_adjustment_set_backdoor <- function(session, xs, ys) .Call(wrap__rs_adjustment_set_backdoor, session, xs, ys)

rs_adjustment_set_optimal <- function(session, xs, ys) .Call(wrap__rs_adjustment_set_optimal, session, xs, ys)

rs_is_valid_backdoor_set <- function(session, xs, ys, z) .Call(wrap__rs_is_valid_backdoor_set, session, xs, ys, z)

rs_all_backdoor_sets <- function(session, xs, ys, minimal, max_size) .Call(wrap__rs_all_backdoor_sets, session, xs, ys, minimal, max_size)

rs_is_valid_adjustment_set_admg <- function(session, xs, ys, z) .Call(wrap__rs_is_valid_adjustment_set_admg, session, xs, ys, z)

rs_all_adjustment_sets_admg <- function(session, xs, ys, minimal, max_size) .Call(wrap__rs_all_adjustment_sets_admg, session, xs, ys, minimal, max_size)

rs_shd <- function(s1, s2) .Call(wrap__rs_shd, s1, s2)

rs_hd <- function(s1, s2) .Call(wrap__rs_hd, s1, s2)

rs_ancestor_aid <- function(s_true, s_guess) .Call(wrap__rs_ancestor_aid, s_true, s_guess)

rs_oset_aid <- function(s_true, s_guess) .Call(wrap__rs_oset_aid, s_true, s_guess)

rs_parent_aid <- function(s_true, s_guess) .Call(wrap__rs_parent_aid, s_true, s_guess)

graph_builder_new <- function(reg, n, simple) .Call(wrap__graph_builder_new, reg, n, simple)

graph_builder_add_edges <- function(b, from, to, etype) invisible(.Call(wrap__graph_builder_add_edges, b, from, to, etype))

graph_builder_resolve_class <- function(b, class) .Call(wrap__graph_builder_resolve_class, b, class)

rs_compute_tiered_layout <- function(session, tier_assignments, num_tiers, orientation) .Call(wrap__rs_compute_tiered_layout, session, tier_assignments, num_tiers, orientation)

rs_write_caugi_file <- function(session, reg, graph_class, path, comment, tags) invisible(.Call(wrap__rs_write_caugi_file, session, reg, graph_class, path, comment, tags))

read_caugi_file <- function(path, reg) .Call(wrap__read_caugi_file, path, reg)

rs_serialize_caugi <- function(session, reg, graph_class, comment, tags) .Call(wrap__rs_serialize_caugi, session, reg, graph_class, comment, tags)

deserialize_caugi <- function(json, reg) .Call(wrap__deserialize_caugi, json, reg)

rs_serialize_graphml <- function(session, reg, graph_class) .Call(wrap__rs_serialize_graphml, session, reg, graph_class)

deserialize_graphml <- function(xml, reg) .Call(wrap__deserialize_graphml, xml, reg)


# nolint end
