# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_caugi_wrappers", use_symbols = TRUE, package_name = "caugi")

#' @usage NULL
#' @useDynLib caugi, .registration = TRUE
NULL

edge_registry_new <- function() .Call(wrap__edge_registry_new)

edge_registry_register_builtins <- function(reg) invisible(.Call(wrap__edge_registry_register_builtins, reg))

edge_registry_seal <- function(reg) invisible(.Call(wrap__edge_registry_seal, reg))

edge_registry_len <- function(reg) .Call(wrap__edge_registry_len, reg)

edge_registry_register <- function(reg, glyph, tail_mark, head_mark, class, symmetric, flags) .Call(wrap__edge_registry_register, reg, glyph, tail_mark, head_mark, class, symmetric, flags)

edge_registry_code_of <- function(reg, glyph) .Call(wrap__edge_registry_code_of, reg, glyph)

graph_builder_new <- function(reg, n, simple) .Call(wrap__graph_builder_new, reg, n, simple)

graph_builder_add_edges <- function(b, from, to, etype) invisible(.Call(wrap__graph_builder_add_edges, b, from, to, etype))

graph_builder_build <- function(b) .Call(wrap__graph_builder_build, b)

graphview_new <- function(core, class) .Call(wrap__graphview_new, core, class)

graph_builder_build_view <- function(b, class) .Call(wrap__graph_builder_build_view, b, class)

parents_of_ptr <- function(g, i) .Call(wrap__parents_of_ptr, g, i)

children_of_ptr <- function(g, i) .Call(wrap__children_of_ptr, g, i)

undirected_of_ptr <- function(g, i) .Call(wrap__undirected_of_ptr, g, i)

neighbors_of_ptr <- function(g, i) .Call(wrap__neighbors_of_ptr, g, i)

ancestors_of_ptr <- function(g, i) .Call(wrap__ancestors_of_ptr, g, i)

descendants_of_ptr <- function(g, i) .Call(wrap__descendants_of_ptr, g, i)

is_simple_ptr <- function(g) .Call(wrap__is_simple_ptr, g)

graph_class_ptr <- function(g) .Call(wrap__graph_class_ptr, g)

is_acyclic_ptr <- function(g) .Call(wrap__is_acyclic_ptr, g)

is_dag_type_ptr <- function(g) .Call(wrap__is_dag_type_ptr, g)

is_pdag_type_ptr <- function(g) .Call(wrap__is_pdag_type_ptr, g)


# nolint end
